//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mens_Beauty_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCustomer
    {
        public int CustomerId { get; set; }
        public int PackageId { get; set; }
        public string NationalID { get; set; }
        public decimal Deposit { get; set; }
        public System.DateTime TakeDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Package Package { get; set; }
    }
}
