//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mens_Beauty_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CoustomerVipDetails
    {
        public string Customer_Name { get; set; }
        public string Customer_Phone { get; set; }
        public string Package_Name { get; set; }
        public string Package_Description { get; set; }
        public decimal Package_Cost { get; set; }
        public decimal Customer_Deposit { get; set; }
        public System.DateTime TakeDate { get; set; }
    }
}
